CREATE TABLE IF NOT EXISTS post_impressions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id         TEXT        NOT NULL,
  user_id         UUID        NOT NULL,
  impression_date DATE        NOT NULL DEFAULT CURRENT_DATE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT post_impressions_unique UNIQUE (post_id, user_id, impression_date)
);

CREATE INDEX IF NOT EXISTS idx_post_impressions_post_id ON post_impressions (post_id);
CREATE INDEX IF NOT EXISTS idx_post_impressions_user_id ON post_impressions (user_id);

ALTER TABLE post_impressions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own impressions"
  ON post_impressions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Aggregation helper: returns total unique-user impression count per post
CREATE OR REPLACE FUNCTION get_impression_counts(p_post_ids TEXT[])
RETURNS TABLE (post_id TEXT, impression_count BIGINT)
LANGUAGE sql STABLE AS $$
  SELECT post_id, COUNT(DISTINCT user_id)::BIGINT AS impression_count
  FROM post_impressions
  WHERE post_id = ANY(p_post_ids)
  GROUP BY post_id;
$$;

-- Chart helper: returns daily impression totals for a user's posts over a date range
CREATE OR REPLACE FUNCTION get_post_impressions_chart(
  p_sender_email TEXT,
  p_start_date   DATE,
  p_end_date     DATE
)
RETURNS TABLE (impression_date DATE, daily_count BIGINT)
LANGUAGE sql STABLE AS $$
  SELECT pi.impression_date, COUNT(DISTINCT pi.user_id)::BIGINT AS daily_count
  FROM post_impressions pi
  JOIN posts p ON p.id::TEXT = pi.post_id
  WHERE LOWER(p.sender) = LOWER(p_sender_email)
    AND pi.impression_date BETWEEN p_start_date AND p_end_date
  GROUP BY pi.impression_date
  ORDER BY pi.impression_date;
$$;
