-- ─── ARTICLES ──────────────────────────────────────────────────────────────

CREATE TABLE articles (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Author (user or guest; company_id = posting as company, same as posts)
  author_uuid     UUID    REFERENCES auth.users(id) ON DELETE CASCADE,
  company_id      INT     REFERENCES companies(id) ON DELETE SET NULL,
  author_type     TEXT    NOT NULL DEFAULT 'user'
                          CHECK (author_type IN ('user', 'guest')),

  -- Guest-only fields
  guest_author_name       TEXT,
  guest_author_bio        TEXT,
  guest_author_avatar_url TEXT,

  -- Content
  title           TEXT    NOT NULL DEFAULT '',
  content         TEXT    NOT NULL DEFAULT '',        -- TipTap HTML, sanitized server-side
  content_plain   TEXT    NOT NULL DEFAULT '',        -- stripped HTML, used for search + read_time
  cover_image_url TEXT,
  excerpt         TEXT,                               -- 160 chars from content_plain, auto-set on publish

  -- Status
  status          TEXT    NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft', 'published')),
  deleted_at      TIMESTAMPTZ,                        -- soft delete; hard-deleted after 30 days

  -- Metadata
  is_pinned           BOOLEAN NOT NULL DEFAULT false,
  is_editors_pick     BOOLEAN NOT NULL DEFAULT false,
  read_time           INT,                            -- ceil(word_count / 200), set on publish

  -- Series
  series_name     TEXT,
  series_order    INT,

  published_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- NO view_count column — tracked via article_impressions to avoid hot-spot writes
);

-- ─── INDEXES ───────────────────────────────────────────────────────────────

-- Main feed: published articles ordered by date (most common query)
CREATE INDEX IF NOT EXISTS idx_articles_feed
  ON articles (published_at DESC)
  WHERE status = 'published' AND deleted_at IS NULL;

-- Author page: articles by user ordered by date
CREATE INDEX IF NOT EXISTS idx_articles_author_uuid
  ON articles (author_uuid, published_at DESC)
  WHERE author_uuid IS NOT NULL AND deleted_at IS NULL;

-- Company articles
CREATE INDEX IF NOT EXISTS idx_articles_company_id
  ON articles (company_id)
  WHERE company_id IS NOT NULL;

-- Drafts: author's own drafts ordered by last update
CREATE INDEX IF NOT EXISTS idx_articles_drafts
  ON articles (author_uuid, updated_at DESC)
  WHERE status = 'draft' AND deleted_at IS NULL;

-- Editor's picks (sparse index — only rows where true)
CREATE INDEX IF NOT EXISTS idx_articles_editors_pick
  ON articles (published_at DESC)
  WHERE is_editors_pick = true AND status = 'published' AND deleted_at IS NULL;

-- Series navigation
CREATE INDEX IF NOT EXISTS idx_articles_series
  ON articles (author_uuid, series_name, series_order)
  WHERE series_name IS NOT NULL AND deleted_at IS NULL;

-- Soft delete cleanup job
CREATE INDEX IF NOT EXISTS idx_articles_deleted_at
  ON articles (deleted_at)
  WHERE deleted_at IS NOT NULL;

-- Full-text search on title + excerpt (simple = language-agnostic, supports Hebrew)
CREATE INDEX IF NOT EXISTS idx_articles_fts
  ON articles USING gin(to_tsvector('simple', title || ' ' || coalesce(excerpt, '')));

-- ─── SKILLS TAGGING ────────────────────────────────────────────────────────

CREATE TABLE article_skills (
  article_id  UUID    NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  skill_id    INT     NOT NULL REFERENCES skills(id)   ON DELETE CASCADE,
  PRIMARY KEY (article_id, skill_id)
);

-- For "articles by skill" discovery queries
CREATE INDEX IF NOT EXISTS idx_article_skills_skill_id
  ON article_skills (skill_id);

-- ─── AUTHOR WRITING PROFILE ────────────────────────────────────────────────

CREATE TABLE article_author_profiles (
  author_uuid UUID    PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  writing_bio TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- topics are derived from article_skills of the author (no separate column needed)
);

-- ─── IMPRESSIONS (mirrors post_impressions pattern) ────────────────────────

CREATE TABLE article_impressions (
  id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id      UUID    NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  user_id         UUID    NOT NULL REFERENCES auth.users(id),
  impression_date DATE    NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT article_impressions_unique UNIQUE (article_id, user_id, impression_date)
);

CREATE INDEX IF NOT EXISTS idx_article_impressions_article_id
  ON article_impressions (article_id);

CREATE INDEX IF NOT EXISTS idx_article_impressions_user_id
  ON article_impressions (user_id);

-- ─── COMMENTS ──────────────────────────────────────────────────────────────

CREATE TABLE article_comments (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id  UUID    NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  author_uuid UUID    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content     TEXT    NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_article_comments_article_id
  ON article_comments (article_id, created_at DESC);

-- ─── RLS ───────────────────────────────────────────────────────────────────

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "articles_read_published_or_own" ON articles FOR SELECT USING (
  deleted_at IS NULL AND (
    status = 'published'
    OR author_uuid = auth.uid()
    OR EXISTS (
      SELECT 1 FROM companies
      WHERE id = company_id AND owner_uuid = auth.uid()
    )
  )
);

CREATE POLICY "articles_author_write" ON articles FOR ALL USING (
  author_uuid = auth.uid()
  OR EXISTS (
    SELECT 1 FROM companies WHERE id = company_id AND owner_uuid = auth.uid()
  )
);

ALTER TABLE article_skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "article_skills_read" ON article_skills FOR SELECT USING (true);

CREATE POLICY "article_skills_author_write" ON article_skills FOR ALL USING (
  EXISTS (
    SELECT 1 FROM articles
    WHERE id = article_id
      AND (author_uuid = auth.uid() OR EXISTS (
        SELECT 1 FROM companies WHERE id = company_id AND owner_uuid = auth.uid()
      ))
  )
);

ALTER TABLE article_author_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "article_author_profiles_read" ON article_author_profiles
  FOR SELECT USING (true);

CREATE POLICY "article_author_profiles_write" ON article_author_profiles
  FOR ALL USING (author_uuid = auth.uid());

ALTER TABLE article_impressions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "article_impressions_read_own" ON article_impressions
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "article_impressions_insert" ON article_impressions
  FOR INSERT WITH CHECK (user_id = auth.uid());

ALTER TABLE article_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "article_comments_read" ON article_comments
  FOR SELECT USING (true);

CREATE POLICY "article_comments_insert" ON article_comments
  FOR INSERT WITH CHECK (author_uuid = auth.uid());

CREATE POLICY "article_comments_delete_own" ON article_comments
  FOR DELETE USING (author_uuid = auth.uid());
